on:
  push:
    branches:
      - release
  workflow_dispatch:
jobs:

  build-arm-template:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Install node
        run: |
          sudo apt install nodejs
          node -v

      - name: install dependencies and build ARM template
        working-directory: ./build
        run: | 
              node --version
              npm --version
              npm install
              
              ### 'run build validate $(Build.Repository.LocalPath)/<Root-folder-from-Git-configuration-settings-in-ADF> /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/<Your-ResourceGroup-Name>/providers/Microsoft.DataFactory/factories/<Your-Factory-Name>'
              npm run build validate ../ /subscriptions/05f19a32-57e6-4417-9d59-5e348bb90a19/resourceGroups/rg-build-adf-test-1/providers/Microsoft.DataFactory/factories/adf-dev-origin-test-1
              
              ### 'run build export $(Build.Repository.LocalPath)/<Root-folder-from-Git-configuration-settings-in-ADF> /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/<Your-ResourceGroup-Name>/providers/Microsoft.DataFactory/factories/<Your-Factory-Name> "ArmTemplate"'
              npm run build export ../ /subscriptions/05f19a32-57e6-4417-9d59-5e348bb90a19/resourceGroups/rg-build-adf-test-1/providers/Microsoft.DataFactory/factories/adf-dev-origin-test-1 armTemplate
      
      - name: Delete linked services
        working-directory: ./build
        run: |
          ls
          node delete-ls.js
      
      - name: Save ARM template in repository
        run: |
          git config --global user.name "jayyei"
          git config --global user.email "sanchezrj0328@gmail.com"
          mv -f build/armTemplate armTemplate/
          git stash
          git fetch
          git checkout -t origin/release-template
          rm -rf build/armTemplate
          mv -f armTemplate build/armTemplate
          git add build/armTemplate/
          git status
          git commit -m "save arm-template"
          git push
          
