on:
  push:
    branches:
      - release
jobs:
  test-az-cli-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Testing azure cli
        run: |
          ls
          cd build/armTemplate
          echo "despues del directorio"
          az login --service-principal -u ab4f0b40-4de8-4e70-a867-a62bf520c662 -p UYf8Q~6dMxYaM4Pi1CFMD2zehxCpzj-sv-pThbed --tenant cd949535-b8e0-4d65-b847-7327e929a415
            --resource-group rg-destination \
            --template-file ARMTemplateForFactory.json \
            --parameters factoryName=mexd2zu1adfcrmmexcomm001 -o json \
            --mode Incremental