on:
  push:
    branches:
      - release
jobs:
  test-az-cli-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Asking for help
        run: |
          az --version
          python --version

      - name: Testing azure cli
        if: false
        uses: azure/powershell@v1
        with:
          azPSVersion: 'latest'
          inlinescript: |
            cd build/armTemplate
            az login --service-principal -u ab4f0b40-4de8-4e70-a867-a62bf520c662 -p UYf8Q~6dMxYaM4Pi1CFMD2zehxCpzj-sv-pThbed --tenant cd949535-b8e0-4d65-b847-7327e929a415
            az deployment group validate --resource-group rg-destination --template-file ARMTemplateForFactory.json --parameters factoryName=mexd2zu1adfcrmmexcomm001 -o json --mode Incremental

      # install Az PowerShell module (necesaria para ejecutar los pre y post scripts)
      - name: Install Az PoweShell module
        run: Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force 
        shell: pwsh
      
      - name: Login and deploy via az module powershell 
        run: |
          $sp = Get-AzADServicePrincipal -DisplayName reg-app
          Write-Host $sp
          # $sp.PasswordCredentials.SecretText
          # $pscredential = Get-Credential -UserName $sp.AppId
          # Connect-AzAccount -ServicePrincipal -Credential $pscredential -Tenant $tenantId
        shell: pwsh

      